#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 15 14:03:28 2022

@author: amikano
"""

import pandas as pd
import matplotlib as mp

url = "https://raw.githubusercontent.com/UVADS/orientation-technical/main/dat/2021-06-15-survey.csv"

df = pd.read_csv(url)

df.hist(bins = 25)

mp.show()

